language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
before_install:
  - git submodule update --init --recursive
before_script:
  #- go get github.com/FiloSottile/Heartbleed
  #- go install github.com/FiloSottile/Heartbleed
  #- which Heartbleed
  - sudo apt-get install nmap
  - sudo apt-get install wget
  - sudo apt-get install unzip
  - sudo apt-get install libcurl4-openssl-dev
  - export SSLYZE_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sslyze/sslyze.py"
  - export SQLMAP_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sqlmap/sqlmap.py"
  - 'cd vendor/Garmr && sudo python setup.py install && cd ../..'
  - 'cd vendor && wget http://downloads.sourceforge.net/project/dirb/dirb/2.03/dirb203.tar.gz && tar xvfz dirb203.tar.gz && cd dirb && ./configure && make && sudo cp dirb /usr/local/bin/ && cd ..'
  - export DIRB_WORDLISTS="/home/travis/build/gauntlt/gauntlt/vendor/dirb/wordlists"

matrix:
  allow_failures:
    - rvm: 2.1.2

notifications:
  irc:
    channels:
      - "chat.freenode.net#gauntlt"
    use_notice: true
